import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const C='9a684d50-2772-43bf-9a5b-1d7e0a399153',A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
test('Postgres migration, account isolation, role restrictions, and atomic review history',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}'); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema public,auth to anon,authenticated,service_role; grant execute on function auth.uid() to anon,authenticated,service_role;`);
 await db.exec(readFileSync(new URL('../supabase/migrations/202609210001_accounts.sql',import.meta.url),'utf8'));
 await db.query('insert into auth.users(id) values($1),($2)',[A,B]);
 await db.query("insert into courses(id,slug,title,language_code) values($1,'hiyaku-1','Class','ja')",[C]);
 assert.equal((await db.query('select join_hiyaku_course($1) as ok',[A])).rows[0].ok,false,'closed course rejects enrollment');
 await db.query('update courses set enrollment_open=true where id=$1',[C]);
 await db.exec('set role service_role');
 await db.query('select join_hiyaku_course($1),join_hiyaku_course($2)',[A,B]);
 await db.exec('reset role');
 await db.query("update course_memberships set role='owner' where user_id=$1",[A]);
 await db.query('select save_course_items($1,$2)',[C,JSON.stringify([{id:'word',lesson:'1',kind:'vocabulary',term:'祭り',definition:'festival',reading:'まつり',source:'Class',notes:'',forms:''}])]);
 const event='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
 const args=[event,A,C,'word','recognition','good',null];
 const first=(await db.query('select record_review($1,$2,$3,$4,$5,$6,$7) as result',args)).rows[0].result;
 const second=(await db.query('select record_review($1,$2,$3,$4,$5,$6,$7) as result',args)).rows[0].result;
 assert.deepEqual(first,second,'retry returns the same review without incrementing progress');
 assert.equal(first.reviews,1);
 await assert.rejects(db.query('select record_review($1,$2,$3,$4,$5,$6,$7)',[event,B,C,'word','recognition','good',null]));
 await db.query('select record_review($1,$2,$3,$4,$5,$6,$7)',['dddddddd-dddd-4ddd-8ddd-dddddddddddd',A,C,'word','production','again','まつり']);
 assert.equal((await db.query('select count(*)::int as n from item_progress')).rows[0].n,2,'recognition and production progress are separate');
 const exercise=(await db.query("insert into practice_exercises(course_id,user_id,target_id,direction,content,model) values($1,$2,'word','en-ja','{}','test') returning id",[C,A])).rows[0].id;
 await db.query("insert into practice_attempts(id,course_id,user_id,exercise_id,answer,status,feedback) values('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',$1,$2,$3,'answer','complete','{\"verdict\":\"correct\"}')",[C,A,exercise]);
 await assert.rejects(db.query("insert into practice_attempts(id,course_id,user_id,exercise_id,answer,status) values('ffffffff-ffff-4fff-8fff-ffffffffffff',$1,$2,$3,'forged','pending')",[C,B,exercise]),'composite foreign key rejects attempts attributed to another account');
 await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[B]);
 assert.equal((await db.query('select count(*)::int as n from learning_items')).rows[0].n,1,'members can read class content');
 for(const table of ['item_progress','review_events','practice_exercises','practice_attempts'])assert.equal((await db.query(`select count(*)::int as n from ${table}`)).rows[0].n,0,table+' is private');
 assert.equal((await db.query('select count(*)::int as n from course_memberships')).rows[0].n,1);
 await assert.rejects(db.query("update course_memberships set role='owner'"));
 await assert.rejects(db.query("update learning_items set data='{}'"));
 await assert.rejects(db.query('select join_hiyaku_course($1)',[B]));
 await assert.rejects(db.query('select reserve_ai_usage($1,$2,1)',[B,C]));
 await assert.rejects(db.query('select record_review($1,$2,$3,$4,$5,$6,$7)',args));
 assert.equal((await db.query('select practice_summary($1) as s',[C])).rows[0].s.reviews,0);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[A]);
 const summary=(await db.query('select practice_summary($1) as s',[C])).rows[0].s;
 assert.equal(summary.reviews,2);assert.equal(summary.sentenceAttempts,1);assert.equal(summary.correctUnassisted,1);
 await db.exec('reset role');
 for(let i=0;i<30;i++)assert.equal((await db.query('select reserve_ai_usage($1,$2,4) as ok',[A,C])).rows[0].ok,true);
 assert.equal((await db.query('select reserve_ai_usage($1,$2,1) as ok',[A,C])).rows[0].ok,false);
 assert.equal((await db.query('select reserve_ai_usage($1,$2,1) as ok',[B,C])).rows[0].ok,true,'independent user allowance');
 await db.exec("update ai_daily_usage set units=2000 where bucket='global'");assert.equal((await db.query('select reserve_ai_usage($1,$2,1) as ok',[B,C])).rows[0].ok,false,'global allowance caps all accounts');
 await db.exec('set role anon');await assert.rejects(db.query('select * from practice_attempts'));await assert.rejects(db.query('select * from learning_items'));
 }finally{await db.close();}
});
