'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Summary={reviews:number;itemsStudied:number;sentenceAttempts:number;correctUnassisted:number;unassistedAttempts:number;activeDays:number};
type Sentence={id:string;answer:string;assisted:boolean;created_at:string;feedback:{verdict:string;feedback:string;correction:string;tip:string};practice_exercises:{content:{japanese:string;translation:string;grammar:string[]};direction:string}};
type Review={id:string;item_snapshot:{term:string;definition:string};skill:string;rating:string;answer:string|null;created_at:string};
type Data={summary:Summary;sentences:Sentence[];reviews:Review[]};
export default function PracticeProgress({enabled}:{enabled:boolean}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0);
 async function load(page:number){setBusy(true);setError('');try{const r=await fetch('/api/progress?offset='+page);const d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error||'Could not load progress.');setData(d);setOffset(page);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
 useEffect(()=>{if(enabled)void load(0);},[enabled]);
 if(!enabled)return <section className="paper mt-6"><h2>Your progress starts here.</h2><p>Sign in and join the class to keep a private history of your reviews, translations, and feedback.</p></section>;
 return <section className="mt-7"><div className="section-head"><div><h2>Your practice, over time.</h2><p>Only you can see your answers and feedback.</p></div><Button variant="outline" disabled={busy} onClick={()=>load(offset)}>Refresh</Button></div>{error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Loading your progress…</p>}{data&&<><div className="progress-stats">{[[data.summary.reviews,'Card reviews'],[data.summary.itemsStudied,'Items practiced'],[data.summary.sentenceAttempts,'Translations checked'],[data.summary.activeDays,'Study days · UTC']].map(([n,l])=><div className="paper" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><p className="my-5">{data.summary.unassistedAttempts?`${data.summary.correctUnassisted} of ${data.summary.unassistedAttempts} unassisted translations assessed correct.`:'Your first unassisted translation will start your accuracy history.'} AI feedback is a study aid, not a course grade. Card ratings are self-assessed.</p>
 <Tabs defaultValue="sentences"><TabsList variant="line"><TabsTrigger value="sentences">Sentence history</TabsTrigger><TabsTrigger value="reviews">Card history</TabsTrigger></TabsList><TabsContent value="sentences"><div className="history-list">{!data.sentences.length?<div className="paper"><h3>{offset?'No more translations':'No translations yet'}</h3><p>Check an answer in Sentences to save your first practice.</p></div>:data.sentences.map(s=><article className="paper" key={s.id}><div className="history-meta"><span>{s.practice_exercises.direction==='en-ja'?'English → Japanese':'Japanese → English'}</span><time dateTime={s.created_at}>{new Date(s.created_at).toLocaleString()}</time></div><h3>{s.practice_exercises.content.grammar.join(' · ')}</h3><p className="history-prompt">{s.practice_exercises.direction==='en-ja'?s.practice_exercises.content.translation:s.practice_exercises.content.japanese}</p><p><strong>Your answer: </strong>{s.answer}</p><span className="badge">{s.feedback.verdict.replaceAll('_',' ')}{s.assisted?' · example viewed':''}</span><details className="mt-4"><summary>Review feedback and example</summary><p>{s.feedback.feedback}</p><p><strong>Suggested answer: </strong>{s.feedback.correction}</p><p>{s.feedback.tip}</p><p>{s.practice_exercises.content.japanese}</p><p>{s.practice_exercises.content.translation}</p></details></article>)}</div></TabsContent><TabsContent value="reviews"><div className="history-list">{!data.reviews.length?<div className="paper"><h3>{offset?'No more reviews':'No card reviews yet'}</h3><p>Review a card and choose how well you remembered it.</p></div>:data.reviews.map(r=><article className="paper" key={r.id}><div className="history-meta"><span>{r.skill==='production'?'Written recall':'Flashcards'} · {r.rating==='good'?'Got it':r.rating}</span><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleString()}</time></div><h3 lang="ja">{r.item_snapshot.term}</h3><p>{r.item_snapshot.definition}</p>{r.answer&&<p>Your answer: {r.answer}</p>}</article>)}</div></TabsContent></Tabs><div className="actions my-5"><Button variant="outline" disabled={busy||!offset} onClick={()=>load(offset-20)}>Newer</Button><span>Page {offset/20+1}</span><Button variant="outline" disabled={busy||(data.sentences.length<20&&data.reviews.length<20)} onClick={()=>load(offset+20)}>Older</Button></div></>}</section>;
}
