'use client';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import GrammarPicker from '@/components/grammar-picker';
import {defaultScope,parseScope,vocabularyInScope,groupLabel,type PracticeScope} from '@/lib/practice-scope';
import type {Entry} from '@/lib/course';
type Exercise={scope:PracticeScope;grammarGroup:string;japanese:string;translation:string;grammar:string[];targetId:string;explanation:string;vocabulary:{term:string;reading:string;meaning:string}[]};
type Feedback={verdict:'correct'|'partly_correct'|'try_again';feedback:string;correction:string;tip:string};
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d:any=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d;}
export default function SentencePractice({entries}:{entries:Entry[]}){
 const [direction,setDirection]=useState('en-ja'),[target,setTarget]=useState('mixed'),[exercise,setExercise]=useState<Exercise|null>(null),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<Feedback|null>(null),[revealed,setRevealed]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[connected,setConnected]=useState<boolean|null>(null),[recent,setRecent]=useState<string[]>([]);
 useEffect(()=>{request('/api/sentence').then(d=>setConnected(d.connected)).catch(()=>setConnected(false));},[]);
 const [scope,setScope]=useState<PracticeScope>(defaultScope),[group,setGroup]=useState('hiyaku-1');
 useEffect(()=>{try{const stored=localStorage.getItem('hiyaku-practice-coverage');if(stored)setScope(parseScope(JSON.parse(stored)));}catch{}},[]);
 function updateScope(next:PracticeScope){setScope(next);try{localStorage.setItem('hiyaku-practice-coverage',JSON.stringify(next));}catch{}}
 const eligible=vocabularyInScope(entries,scope);
 const grammar=entries.filter(e=>e.kind==='grammar');
 async function generate(){setBusy('generate');setError('');try{const d=await request('/api/sentence',{target,grammarGroup:group,scope,recent});setExercise(d);setRecent(r=>[...r,d.japanese].slice(-5));setAnswer('');setFeedback(null);setRevealed(false);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy('');}}
 async function check(){if(!exercise)return;setBusy('check');setError('');try{setFeedback(await request('/api/feedback',{...exercise,answer,direction}));setRevealed(true);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy('');}}
 return <div className="study-grid"><section className="paper"><p className="eyebrow">YOUR CLASS, IN CONTEXT</p><h2>Make the grammar yours.</h2><p>Translate a new sentence, then get feedback on meaning and grammar. Pick your grammar focus and the vocabulary you have covered.</p>
 <div className="actions my-5" aria-label="Translation direction"><Button variant={direction==='en-ja'?'default':'outline'} aria-pressed={direction==='en-ja'} disabled={!!busy} onClick={()=>{setDirection('en-ja');setExercise(null);setFeedback(null);}}>English → Japanese</Button><Button variant={direction==='ja-en'?'default':'outline'} aria-pressed={direction==='ja-en'} disabled={!!busy} onClick={()=>{setDirection('ja-en');setExercise(null);setFeedback(null);}}>Japanese → English</Button></div>
 <div className="rounded-xl border p-4 my-5"><Tabs defaultValue="grammar"><TabsList variant="line" className="w-full mb-4"><TabsTrigger value="grammar">Grammar focus</TabsTrigger><TabsTrigger value="coverage">Vocabulary coverage</TabsTrigger></TabsList>
 <TabsContent value="grammar"><GrammarPicker entries={entries} group={group} target={target} disabled={!!busy} onChange={(g,t)=>{setGroup(g);setTarget(t);}}/><p className="text-sm opacity-65 mt-3">Choose a whole chapter for mixed practice, or focus on one pattern.</p></TabsContent>
 <TabsContent value="coverage"><h3 className="text-lg">Genki vocabulary through chapter {scope.genkiThrough}</h3><p className="text-sm mt-1 mb-4">Select your latest completed chapter. Earlier chapters and introductory greetings stay included.</p>{[{label:'Genki I',start:1,end:12},{label:'Genki II',start:13,end:23}].map(book=><fieldset key={book.label} className="mb-4" disabled={!!busy}><legend className="text-sm font-medium mb-2">{book.label}</legend><div className="grid grid-cols-6 gap-2">{Array.from({length:book.end-book.start+1},(_,i)=>i+book.start).map(ch=><Button key={ch} variant={scope.genkiThrough===ch?'default':'outline'} aria-label={'Use vocabulary through Genki chapter '+ch} aria-pressed={scope.genkiThrough===ch} onClick={()=>updateScope({...scope,genkiThrough:ch})}>{ch}</Button>)}</div></fieldset>)}<label className="flex items-center gap-3 mt-4"><Checkbox checked={scope.includeHiyaku} disabled={!!busy} onCheckedChange={checked=>updateScope({...scope,includeHiyaku:checked})}/><span>Include Hiyaku & other saved class words</span></label><p className="text-sm opacity-65 mt-3">Chapter labels come from the spreadsheet’s earliest lesson reference, including reading sections. This limits vocabulary; your grammar focus is selected separately.</p></TabsContent></Tabs><div className="mt-4 pt-3 border-t flex flex-wrap gap-2 text-sm"><span className="badge">Genki 1–{scope.genkiThrough}</span>{scope.includeHiyaku&&<span className="badge">+ Hiyaku / class words</span>}<span className="ml-auto">{eligible.length.toLocaleString()} eligible entries</span></div></div>
 <div className="actions mt-4"><Button disabled={!!busy||connected!==true||!grammar.length} onClick={generate}>{busy==='generate'?'Creating and checking…':exercise?'Next sentence ↗':'Create a sentence ↗'}</Button><small aria-live="polite">{connected===null?'Checking connection…':connected?'AI connected':'AI connection unavailable'}</small></div>
 {error&&<p role="alert" className="error mt-4">{error}</p>}
 {connected===false&&<p className="notice">The AI connection needs attention. Your library and flashcards still work.</p>}
 {exercise&&<div className="sentence"><p className="eyebrow">{direction==='en-ja'?'WRITE IN JAPANESE':'WRITE THE MEANING IN ENGLISH'}</p><p lang={direction==='en-ja'?'en':'ja'}>{direction==='en-ja'?exercise.translation:exercise.japanese}</p><small>Target: {exercise.grammar.join(' · ')} · {groupLabel(exercise.grammarGroup)}<br/>Vocabulary: Genki 1–{exercise.scope.genkiThrough}{exercise.scope.includeHiyaku?' + class words':''}</small><label htmlFor="translation-answer" className="mt-5">Your translation</label><textarea id="translation-answer" lang={direction==='en-ja'?'ja':'en'} rows={3} value={answer} disabled={!!busy} onChange={e=>{setAnswer(e.target.value);setFeedback(null);}} placeholder={direction==='en-ja'?'日本語で書いてください…':'What does the sentence mean?'} />
 <div className="actions mt-4"><Button disabled={!!busy||!answer.trim()} onClick={check}>{busy==='check'?'Reading your answer…':'Check my answer'}</Button><Button variant="outline" disabled={!!busy} onClick={()=>setRevealed(!revealed)}>{revealed?'Hide example':'Show an example answer'}</Button></div>
 {feedback&&<div className="notice mt-5" role="status"><h3>{feedback.verdict==='correct'?'You’ve got it':feedback.verdict==='partly_correct'?'Close — a small adjustment':'Let’s work through it'}</h3><p>{feedback.feedback}</p><p><strong>Suggested answer: </strong>{feedback.correction}</p><p>{feedback.tip}</p></div>}
 {revealed&&<div className="mt-5"><p className="eyebrow">ONE POSSIBLE ANSWER</p><p lang={direction==='en-ja'?'ja':'en'}>{direction==='en-ja'?exercise.japanese:exercise.translation}</p><p>{exercise.explanation}</p><details><summary>Words used from your class</summary>{exercise.vocabulary.map((v,i)=><p key={i}><b>{v.term}</b> {v.reading&&`(${v.reading})`} — {v.meaning}</p>)}</details></div>}
 </div>}</section><aside><h2>Your course boundary</h2><p><b>{eligible.length.toLocaleString()}</b> eligible vocabulary entries<br/><b>{grammar.length}</b> grammar study entries</p><p>New sentences use your selected vocabulary coverage. Changing settings applies to the next sentence. Word forms and kanji are checked before it appears.</p><p>Words with kanji outside your saved individual-kanji list appear in kana. Genki vocabulary spellings are preserved in your library.</p><p className="notice">A second AI check reviews naturalness, translation, and grammar coverage. This can still miss mistakes. Valid alternative translations are welcome.</p></aside></div>
}
