'use client';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {Entry} from '@/lib/course';
type Exercise={japanese:string;translation:string;grammar:string[];targetId:string;explanation:string;vocabulary:{term:string;reading:string;meaning:string}[]};
type Feedback={verdict:'correct'|'partly_correct'|'try_again';feedback:string;correction:string;tip:string};
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d:any=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d;}
export default function SentencePractice({entries}:{entries:Entry[]}){
 const [direction,setDirection]=useState('en-ja'),[target,setTarget]=useState('mixed'),[exercise,setExercise]=useState<Exercise|null>(null),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<Feedback|null>(null),[revealed,setRevealed]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[connected,setConnected]=useState<boolean|null>(null),[recent,setRecent]=useState<string[]>([]);
 useEffect(()=>{request('/api/sentence').then(d=>setConnected(d.connected)).catch(()=>setConnected(false));},[]);
 const grammar=entries.filter(e=>e.kind==='grammar');
 async function generate(){setBusy('generate');setError('');try{const d=await request('/api/sentence',{target,recent});setExercise(d);setRecent(r=>[...r,d.japanese].slice(-5));setAnswer('');setFeedback(null);setRevealed(false);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy('');}}
 async function check(){if(!exercise)return;setBusy('check');setError('');try{setFeedback(await request('/api/feedback',{...exercise,answer,direction}));setRevealed(true);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy('');}}
 return <div className="study-grid"><section className="paper"><p className="eyebrow">YOUR CLASS, IN CONTEXT</p><h2>Make the grammar yours.</h2><p>Translate a new sentence, then get feedback on meaning and grammar. Your foundation is Genki I & II; your new material is Hiyaku chapter 1.</p>
 <div className="actions my-5" aria-label="Translation direction"><Button variant={direction==='en-ja'?'default':'outline'} aria-pressed={direction==='en-ja'} disabled={!!busy} onClick={()=>{setDirection('en-ja');setExercise(null);setFeedback(null);}}>English → Japanese</Button><Button variant={direction==='ja-en'?'default':'outline'} aria-pressed={direction==='ja-en'} disabled={!!busy} onClick={()=>{setDirection('ja-en');setExercise(null);setFeedback(null);}}>Japanese → English</Button></div>
 <label htmlFor="grammar-target">Grammar to practice</label><Select value={target} onValueChange={v=>{if(v)setTarget(v);}} disabled={!!busy}><SelectTrigger id="grammar-target" className="w-full"><SelectValue>{target==='mixed'?'Mix my nine Hiyaku grammar points':grammar.find(g=>g.id===target)?.term||target}</SelectValue></SelectTrigger><SelectContent><SelectItem value="mixed">Mix my nine Hiyaku grammar points</SelectItem>{[...grammar].sort((a,b)=>Number(b.id.startsWith('hiyaku'))-Number(a.id.startsWith('hiyaku'))).map(g=><SelectItem key={g.id} value={g.id}>{g.term} · {g.lesson==='1'?'Hiyaku 1':g.lesson}</SelectItem>)}</SelectContent></Select>
 <div className="actions mt-4"><Button disabled={!!busy||connected!==true||!grammar.length} onClick={generate}>{busy==='generate'?'Creating and checking…':exercise?'Next sentence ↗':'Create a sentence ↗'}</Button><small aria-live="polite">{connected===null?'Checking connection…':connected?'AI connected':'AI connection unavailable'}</small></div>
 {error&&<p role="alert" className="error mt-4">{error}</p>}
 {connected===false&&<p className="notice">The AI connection needs attention. Your library and flashcards still work.</p>}
 {exercise&&<div className="sentence"><p className="eyebrow">{direction==='en-ja'?'WRITE IN JAPANESE':'WRITE THE MEANING IN ENGLISH'}</p><p lang={direction==='en-ja'?'en':'ja'}>{direction==='en-ja'?exercise.translation:exercise.japanese}</p><small>Target: {exercise.grammar.join(' · ')}</small><label htmlFor="translation-answer" className="mt-5">Your translation</label><textarea id="translation-answer" lang={direction==='en-ja'?'ja':'en'} rows={3} value={answer} disabled={!!busy} onChange={e=>{setAnswer(e.target.value);setFeedback(null);}} placeholder={direction==='en-ja'?'日本語で書いてください…':'What does the sentence mean?'} />
 <div className="actions mt-4"><Button disabled={!!busy||!answer.trim()} onClick={check}>{busy==='check'?'Reading your answer…':'Check my answer'}</Button><Button variant="outline" disabled={!!busy} onClick={()=>setRevealed(!revealed)}>{revealed?'Hide example':'Show an example answer'}</Button></div>
 {feedback&&<div className="notice mt-5" role="status"><h3>{feedback.verdict==='correct'?'You’ve got it':feedback.verdict==='partly_correct'?'Close — a small adjustment':'Let’s work through it'}</h3><p>{feedback.feedback}</p><p><strong>Suggested answer: </strong>{feedback.correction}</p><p>{feedback.tip}</p></div>}
 {revealed&&<div className="mt-5"><p className="eyebrow">ONE POSSIBLE ANSWER</p><p lang={direction==='en-ja'?'ja':'en'}>{direction==='en-ja'?exercise.japanese:exercise.translation}</p><p>{exercise.explanation}</p><details><summary>Words used from your class</summary>{exercise.vocabulary.map((v,i)=><p key={i}><b>{v.term}</b> {v.reading&&`(${v.reading})`} — {v.meaning}</p>)}</details></div>}
 </div>}</section><aside><h2>Your course boundary</h2><p><b>{entries.filter(e=>e.kind==='vocabulary').length.toLocaleString()}</b> vocabulary entries<br/><b>{grammar.length}</b> grammar study entries</p><p>Each sentence draws from a rotating selection of your saved vocabulary. Word forms and kanji are checked before it appears.</p><p>Words with kanji outside your saved individual-kanji list appear in kana. Genki vocabulary spellings are preserved in your library.</p><p className="notice">A second AI check reviews naturalness, translation, and grammar coverage. This can still miss mistakes. Valid alternative translations are welcome.</p></aside></div>
}
