export type Entry={id:string;term:string;definition:string;reading:string;kind:"vocabulary"|"kanji"|"grammar";lesson:string;source:string;notes:string;forms:string};
export type Review={id:string;due:number;days:number;reviews:number};
export const seed:Entry={id:"quizlet-515584685-1",term:"みなさん",definition:"everyone",reading:"みなさん",kind:"vocabulary",lesson:"1",source:"https://quizlet.com/515584685/flashcards",notes:"Observed first card of 48. Source extraction is incomplete.",forms:"みなさん"};
export const sources=[{url:"https://quizlet.com/1211218072/edit",name:"『飛躍』第一課 語彙",status:"95 cards · full extraction still pending",count:null},{url:"https://quizlet.com/515584685/flashcards",name:"『飛躍』第一課 漢字",status:"Collected · all 48 cards",count:48},{url:"https://docs.google.com/spreadsheets/d/1LvkY5vxgrt2rBTHXwHKPLZ3bbnEdedH-/edit#gid=1137479501",name:"Genki I & II vocabulary",status:"Imported · 1,774 index entries",count:1774},{url:"https://bookclub2.japantimes.co.jp/download/files/genki3/genki-3rd_syllabus_E.pdf",name:"Genki I & II core grammar",status:"137 study entries · 3rd edition syllabus",count:137}];
export function validateEntry(value:unknown):Entry{if(!value||typeof value!=="object")throw Error("Invalid entry");const e=value as Record<string,unknown>;for(const k of ["id","term","definition","reading","kind","lesson","source","notes","forms"])if(typeof e[k]!=="string"||(e[k] as string).length>4000)throw Error("Invalid "+k);if(!(e.term as string).trim()||!(e.definition as string).trim())throw Error("Each entry needs a term and definition.");if(!["vocabulary","kanji","grammar"].includes(e.kind as string))throw Error("Choose vocabulary, kanji, or grammar.");if(!/^[a-zA-Z0-9_-]{1,100}$/.test(e.id as string))throw Error("Invalid entry ID");return Object.fromEntries(Object.entries(e).map(([k,v])=>[k,typeof v==="string"?v.trim():v])) as Entry;}
export function nextReview(old:Review|undefined,rating:string,now=Date.now()):Review{const days=rating==="again"?0:rating==="hard"?1:Math.min(90,Math.max(1,(old?.days||0)*2||1));return {id:old?.id||"",days,due:now+(days?days*86400000:600000),reviews:(old?.reviews||0)+1};}
export function parseDelimited(text:string):string[][]{text=text.replace(/^\uFEFF/,"");const delimiter=text.split(/\r?\n/)[0].includes("\t")?"\t":",";let rows:string[][]=[],row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===delimiter&&!quoted){row.push(field);field="";}else if(c==='\n'&&!quoted){row.push(field.replace(/\r$/, ""));rows.push(row);row=[];field="";}else field+=c;}if(quoted)throw Error("Unclosed quote in spreadsheet text.");if(field||row.length){row.push(field.replace(/\r$/, ""));rows.push(row);}return rows.filter(r=>r.some(c=>c.trim()));}
export function csv(entries:Entry[]){const keys=(Object.keys(seed) as (keyof Entry)[]);const cell=(s:string)=>'"'+(/^[=+@\-\t\r]/.test(s)?"'":"")+s.replaceAll('"','""')+'"';return '\uFEFF'+[keys.join(","),...entries.map(e=>keys.map(k=>cell(e[k])).join(","))].join("\r\n");}
export function compose(tokens:string[],registry:Record<string,string>):string{if(!Array.isArray(tokens)||tokens.length<2||tokens.length>60||tokens.some(t=>!Object.hasOwn(registry,t)))throw Error("Sentence used an unapproved word form.");return tokens.map(t=>registry[t]).join("");}
